name: main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
          server-id: github
      - name: Version
        run: >-
          mvn
          build-helper:parse-version
          versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.incrementalVersion}-SNAPSHOT-$( git rev-parse --short HEAD )
          versions:commit
      - name: Test
        run: mvn test
      - name: Build
        run: mvn --batch-mode --define maven.test.skip package
      - name: Publish
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
